#!/usr/bin/env bash

COOKIES_FILE=admin_cookies
URL=http://localhost:8080

if ! [ -e "$COOKIES_FILE" ]
then
  echo "No cookie file, creating at $COOKIES_FILE."
  curl -L -c $COOKIES_FILE "$URL/_auth_middleware/admin?token=SUPER_SECRET_TOKEN" &> /dev/null
fi

ROUTE=$1
DATA=$2

if [ -z "$ROUTE" ]
then
  echo "Usage: ./request URL [DATA]"
  exit 1
fi

if [ -z "$DATA" ]
then
  curl -b "$COOKIES_FILE" "$URL/api/$ROUTE"
else
  curl -b "$COOKIES_FILE" "$URL/api/$ROUTE" -d "$DATA" -H "Content-Type: application/json"
fi
